package dal

import (
	"fmt"
	"math/rand/v2"
	"strings"
)

type PduDao struct {
	data []string
}

// GetRandomPdu implements IPduDao.
func (p *PduDao) GetRandomPdu(maxOperations int) string {
	r := rand.IntN(maxOperations)
	sb := strings.Builder{}
	for i := 0; i < r; i++ {
		sb.WriteString(p.data[rand.IntN(len(p.data))])
	}
	return fmt.Sprintf("<?xml version=\"1.0\" encoding=\"iso-8859-15\" standalone=\"yes\"?> <pdu> <order-list count=\"%d\">%s</order-list> </pdu>", r, sb.String())
}

func NewPduDao() ITestDataDao {
	return &PduDao{
		data: []string{
			"",
			"<order index=\"1\"> <key>AL12345</key> <origin tid=\"300012\">Wien</origin> <receive-tad>2025-06-05 09:21:01</receive-tad> <operation-id>BWSt40001</operation-id> <level>2</level> <name>Thomas Müller</name> <operation-name>BRAND BAUM-, FLUR-, BÖSCHUNG</operation-name> <caller>+55 699 1234567</caller> <location>Stephansplatz 3, 1010 Wien</location> <info>Brennender Baum im Stadtpark</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"2\"> <destination index=\"1\" id=\"D10001\">FF-Wien-Innere Stadt</destination> <destination index=\"2\" id=\"D10002\">FF-Wien-Leopoldstadt</destination> </destination-list> </order>",
			"<order index=\"2\"> <key>AL12346</key> <origin tid=\"300012\">Graz</origin> <receive-tad>2025-06-05 10:15:22</receive-tad> <operation-id>BWSt40002</operation-id> <level>1</level> <name>Anna Hofer</name> <operation-name>TE TIERRETTUNG</operation-name> <caller>+55 664 9876543</caller> <location>Hauptplatz 14, 8010 Graz</location> <info>Katze auf Baum</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"1\"> <destination index=\"1\" id=\"D20001\">FF-Graz-Innere Stadt</destination> </destination-list> </order>",
			"<order index=\"3\"> <key>AL12347</key> <origin tid=\"300012\">Salzburg</origin> <receive-tad>2025-06-05 11:30:45</receive-tad> <operation-id>BWSt40003</operation-id> <level>3</level> <name>Michael Gruber</name> <operation-name>BRAND WOHNHAUS</operation-name> <caller>+55 676 5551234</caller> <location>Getreidegasse 9, 5020 Salzburg</location> <info>Rauchentwicklung im Dachgeschoss</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"3\"> <destination index=\"1\" id=\"D30001\">FF-Salzburg-Altstadt</destination> <destination index=\"2\" id=\"D30002\">FF-Salzburg-Maxglan</destination> <destination index=\"3\" id=\"D30003\">FF-Salzburg-Aigen</destination> </destination-list> </order>",
			"<order index=\"4\"> <key>AL12348</key> <origin tid=\"300012\">Innsbruck</origin> <receive-tad>2025-06-05 12:45:33</receive-tad> <operation-id>BWSt40004</operation-id> <level>2</level> <name>Elisabeth Wagner</name> <operation-name>TE VERKEHRSUNFALL</operation-name> <caller>+55 650 7778899</caller> <location>Maria-Theresien-Straße 18, 6020 Innsbruck</location> <info>PKW gegen Laternenmast</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"2\"> <destination index=\"1\" id=\"D40001\">FF-Innsbruck-Stadt</destination> <destination index=\"2\" id=\"D40002\">FF-Innsbruck-Wilten</destination> </destination-list> </order>",
			"<order index=\"5\"> <key>AL12349</key> <origin tid=\"300012\">Linz</origin> <receive-tad>2025-06-05 13:10:17</receive-tad> <operation-id>BWSt40005</operation-id> <level>3</level> <name>Josef Bauer</name> <operation-name>BRAND INDUSTRIEGEBÄUDE</operation-name> <caller>+55 677 1112233</caller> <location>Landstraße 17, 4020 Linz</location> <info>Starke Rauchentwicklung aus Lagerhalle</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"3\"> <destination index=\"1\" id=\"D50001\">FF-Linz-Stadt</destination> <destination index=\"2\" id=\"D50002\">FF-Linz-Ebelsberg</destination> <destination index=\"3\" id=\"D50003\">FF-Linz-Pichling</destination> </destination-list> </order>",
			"<order index=\"6\"> <key>AL12350</key> <origin tid=\"300012\">Klagenfurt</origin> <receive-tad>2025-06-05 14:05:39</receive-tad> <operation-id>BWSt40006</operation-id> <level>1</level> <name>Maria Huber</name> <operation-name>TE WASSERSCHADEN</operation-name> <caller>+55 664 2223344</caller> <location>Neuer Platz 1, 9020 Klagenfurt</location> <info>Wasserrohrbruch im Keller</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"1\"> <destination index=\"1\" id=\"D60001\">FF-Klagenfurt-Stadt</destination> </destination-list> </order>",
			"<order index=\"7\"> <key>AL12351</key> <origin tid=\"300012\">Villach</origin> <receive-tad>2025-06-05 15:20:11</receive-tad> <operation-id>BWSt40007</operation-id> <level>2</level> <name>Andreas Maier</name> <operation-name>BRAND PKW</operation-name> <caller>+55 676 4445566</caller> <location>Hauptplatz 5, 9500 Villach</location> <info>Fahrzeugbrand auf Parkplatz</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"2\"> <destination index=\"1\" id=\"D70001\">FF-Villach-Stadt</destination> <destination index=\"2\" id=\"D70002\">FF-Villach-Land</destination> </destination-list> </order>",
			"<order index=\"8\"> <key>AL12352</key> <origin tid=\"300012\">St. Pölten</origin> <receive-tad>2025-06-05 16:35:27</receive-tad> <operation-id>BWSt40008</operation-id> <level>2</level> <name>Julia Berger</name> <operation-name>TE STURMSCHADEN</operation-name> <caller>+55 650 6667788</caller> <location>Rathausplatz 1, 3100 St. Pölten</location> <info>Baum auf Straße gestürzt</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"2\"> <destination index=\"1\" id=\"D80001\">FF-St. Pölten-Stadt</destination> <destination index=\"2\" id=\"D80002\">FF-St. Pölten-Wagram</destination> </destination-list> </order>",
			"<order index=\"9\"> <key>AL12353</key> <origin tid=\"300012\">Eisenstadt</origin> <receive-tad>2025-06-05 17:40:58</receive-tad> <operation-id>BWSt40009</operation-id> <level>1</level> <name>Stefan Eder</name> <operation-name>BRAND MÜLLCONTAINER</operation-name> <caller>+55 677 8889900</caller> <location>Hauptstraße 35, 7000 Eisenstadt</location> <info>Brennender Müllcontainer hinter Supermarkt</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"1\"> <destination index=\"1\" id=\"D90001\">FF-Eisenstadt</destination> </destination-list> </order>",
			"<order index=\"10\"> <key>AL12354</key> <origin tid=\"300012\">Bregenz</origin> <receive-tad>2025-06-05 18:15:42</receive-tad> <operation-id>BWSt40010</operation-id> <level>3</level> <name>Katharina Schmid</name> <operation-name>TE PERSONENRETTUNG</operation-name> <caller>+55 699 3334455</caller> <location>Seepromenade 2, 6900 Bregenz</location> <info>Person im Bodensee in Not</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"3\"> <destination index=\"1\" id=\"D10101\">FF-Bregenz-Stadt</destination> <destination index=\"2\" id=\"D10102\">FF-Bregenz-Vorkloster</destination> <destination index=\"3\" id=\"D10103\">Wasserrettung Bregenz</destination> </destination-list> </order>",
			"<order index=\"11\"> <key>AL12355</key> <origin tid=\"300012\">Dornbirn</origin> <receive-tad>2025-06-05 19:25:33</receive-tad> <operation-id>BWSt40011</operation-id> <level>3</level> <name>Martin Fischer</name> <operation-name>BRAND GEWERBE/INDUSTRIE</operation-name> <caller>+55 664 5556677</caller> <location>Marktplatz 1, 6850 Dornbirn</location> <info>Feuer in Produktionshalle</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"3\"> <destination index=\"1\" id=\"D10201\">FF-Dornbirn-Stadt</destination> <destination index=\"2\" id=\"D10202\">FF-Dornbirn-Hatlerdorf</destination> <destination index=\"3\" id=\"D10203\">FF-Dornbirn-Oberdorf</destination> </destination-list> </order>",
			"<order index=\"12\"> <key>AL12356</key> <origin tid=\"300012\">Wiener Neustadt</origin> <receive-tad>2025-06-05 20:10:19</receive-tad> <operation-id>BWSt40012</operation-id> <level>2</level> <name>Sandra König</name> <operation-name>TE VERKEHRSUNFALL</operation-name> <caller>+55 676 7778899</caller> <location>Wiener Straße 25, 2700 Wiener Neustadt</location> <info>Verkehrsunfall mit eingeklemmter Person</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"2\"> <destination index=\"1\" id=\"D10301\">FF-Wiener Neustadt</destination> <destination index=\"2\" id=\"D10302\">FF-Wiener Neustadt-Nord</destination> </destination-list> </order>",
			"<order index=\"13\"> <key>AL12357</key> <origin tid=\"300012\">Baden</origin> <receive-tad>2025-06-05 21:05:47</receive-tad> <operation-id>BWSt40013</operation-id> <level>3</level> <name>Peter Schwarz</name> <operation-name>BRAND WOHNHAUS</operation-name> <caller>+55 650 9990001</caller> <location>Hauptplatz 10, 2500 Baden</location> <info>Küchenbrand im 2. Stock</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"3\"> <destination index=\"1\" id=\"D10401\">FF-Baden-Stadt</destination> <destination index=\"2\" id=\"D10402\">FF-Baden-Leesdorf</destination> <destination index=\"3\" id=\"D10403\">FF-Baden-Weikersdorf</destination> </destination-list> </order>",
			"<order index=\"14\"> <key>AL12358</key> <origin tid=\"300012\">Steyr</origin> <receive-tad>2025-06-05 22:15:36</receive-tad> <operation-id>BWSt40014</operation-id> <level>2</level> <name>Christian Wolf</name> <operation-name>TE HOCHWASSER</operation-name> <caller>+55 677 1122334</caller> <location>Stadtplatz 27, 4400 Steyr</location> <info>Überflutung nach Starkregen</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"2\"> <destination index=\"1\" id=\"D10501\">FF-Steyr-Stadt</destination> <destination index=\"2\" id=\"D10502\">FF-Steyr-Christkindl</destination> </destination-list> </order>",
			"<order index=\"15\"> <key>AL12359</key> <origin tid=\"300012\">Wels</origin> <receive-tad>2025-06-05 23:20:14</receive-tad> <operation-id>BWSt40015</operation-id> <level>2</level> <name>Sabine Binder</name> <operation-name>BRAND ELEKTRISCHE ANLAGEN</operation-name> <caller>+55 699 4455667</caller> <location>Ringstraße 4, 4600 Wels</location> <info>Rauchentwicklung aus Trafostation</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"2\"> <destination index=\"1\" id=\"D10601\">FF-Wels</destination> <destination index=\"2\" id=\"D10602\">FF-Wels-Pernau</destination> </destination-list> </order>",
			"<order index=\"16\"> <key>AL12360</key> <origin tid=\"300012\">Klosterneuburg</origin> <receive-tad>2025-06-06 00:30:55</receive-tad> <operation-id>BWSt40016</operation-id> <level>1</level> <name>Robert Fuchs</name> <operation-name>TE STURMSCHADEN</operation-name> <caller>+55 664 7788990</caller> <location>Rathausplatz 1, 3400 Klosterneuburg</location> <info>Umgestürzter Baum auf Fahrbahn</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"1\"> <destination index=\"1\" id=\"D10701\">FF-Klosterneuburg</destination> </destination-list> </order>",
			"<order index=\"17\"> <key>AL12361</key> <origin tid=\"300012\">Leoben</origin> <receive-tad>2025-06-06 01:45:22</receive-tad> <operation-id>BWSt40017</operation-id> <level>1</level> <name>Monika Steiner</name> <operation-name>BRAND SONSTIGES</operation-name> <caller>+55 676 8899001</caller> <location>Hauptplatz 12, 8700 Leoben</location> <info>Brennender Abfallkorb</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"1\"> <destination index=\"1\" id=\"D10801\">FF-Leoben-Stadt</destination> </destination-list> </order>",
			"<order index=\"18\"> <key>AL12362</key> <origin tid=\"300012\">Krems</origin> <receive-tad>2025-06-06 02:55:18</receive-tad> <operation-id>BWSt40018</operation-id> <level>1</level> <name>Markus Lang</name> <operation-name>TE WASSERSCHADEN</operation-name> <caller>+55 650 2233445</caller> <location>Obere Landstraße 8, 3500 Krems</location> <info>Wassereinbruch im Keller</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"1\"> <destination index=\"1\" id=\"D10901\">FF-Krems-Stadt</destination> </destination-list> </order>",
			"<order index=\"19\"> <key>AL12363</key> <origin tid=\"300012\">Amstetten</origin> <receive-tad>2025-06-06 03:40:09</receive-tad> <operation-id>BWSt40019</operation-id> <level>3</level> <name>Daniel Huber</name> <operation-name>BRAND LANDWIRTSCHAFT</operation-name> <caller>+55 677 3344556</caller> <location>Hauptplatz 37, 3300 Amstetten</location> <info>Scheunenbrand mit Übergriffsgefahr</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"3\"> <destination index=\"1\" id=\"D11001\">FF-Amstetten</destination> <destination index=\"2\" id=\"D11002\">FF-Amstetten-Hausmening</destination> <destination index=\"3\" id=\"D11003\">FF-Amstetten-Neufurth</destination> </destination-list> </order>",
			"<order index=\"20\"> <key>AL12364</key> <origin tid=\"300012\">Feldkirch</origin> <receive-tad>2025-06-06 04:25:33</receive-tad> <operation-id>BWSt40020</operation-id> <level>2</level> <name>Verena Maier</name> <operation-name>TE PERSONENRETTUNG</operation-name> <caller>+55 699 5566778</caller> <location>Marktgasse 2, 6800 Feldkirch</location> <info>Person in Aufzug eingeschlossen</info> <program>Feuer</program> <status>Alarmiert</status> <watch-out-tad></watch-out-tad> <finished-tad></finished-tad> <destination-list count=\"2\"> <destination index=\"1\" id=\"D11101\">FF-Feldkirch-Stadt</destination> <destination index=\"2\" id=\"D11102\">FF-Feldkirch-Nofels</destination> </destination-list> </order>",
		},
	}
}
